#!/usr/bin/env sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<SQL
CREATE ROLE ${RAW_USER} LOGIN PASSWORD '${RAW_PASSWORD}';
CREATE ROLE ${AIRFLOW_DB_USER} LOGIN PASSWORD '${AIRFLOW_DB_PASSWORD}';
CREATE ROLE ${SUPERSET_DB_USER} LOGIN PASSWORD '${SUPERSET_DB_PASSWORD}';

CREATE DATABASE ${RAW_DB} OWNER ${RAW_USER};
CREATE DATABASE ${AIRFLOW_DB} OWNER ${AIRFLOW_DB_USER};
CREATE DATABASE ${SUPERSET_DB} OWNER ${SUPERSET_DB_USER};
SQL
