\connect rawdb;

CREATE SCHEMA IF NOT EXISTS raw AUTHORIZATION raw_user;

GRANT USAGE, CREATE ON SCHEMA raw TO raw_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA raw GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO raw_user;
